"""Line specification for the D2C MIS workbook.

Everything the generator needs to know about a line lives here: where it sits, which channel types and
archetypes it applies to, how it is computed, and the note a founder sees when they hover the label.
Edit this file to change wording or add lines; build_mis.py only lays things out.
"""

# ---------------------------------------------------------------------------------------------------
# Channel types. A channel in config is {"name": "Amazon", "type": "amazon"}.
# ---------------------------------------------------------------------------------------------------
CHANNEL_TYPES = {
    "website": {
        "label": "Own website",
        "commission_mode": None,          # no partner margin
        "has_pg": True,
        "has_ship_fee": True,
        "mkt_label": "Performance marketing (Meta, Google, affiliates)",
        "mkt_where": "Meta Ads Manager and Google Ads billing for the month, excluding GST. Add affiliate and influencer payouts tied to sales.",
        "gmv_where": "Shopify › Analytics › Gross sales (before discounts, returns and shipping). Woo/Magento: sum of order value incl. GST.",
        "disc_where": "Shopify › Analytics › Discounts.",
        "returns_where": "Shopify › Analytics › Returns, plus RTO value from your courier or Shiprocket RTO report.",
        "gst_default": None,
    },
    "amazon": {
        "label": "Amazon",
        "commission_mode": "billed",      # platform bills referral fee; brand invoices the shopper
        "has_pg": False,
        "has_ship_fee": False,
        "mkt_label": "Amazon Ads (Sponsored Products / Brands)",
        "mkt_where": "Amazon Advertising console › Campaign manager, spend for the month excluding GST.",
        "gmv_where": "Seller Central › Business Reports › Ordered product sales (incl. GST).",
        "disc_where": "Coupons, Lightning Deals and promo codes you funded: Seller Central › Payments › Transaction view › Promotion rebates.",
        "returns_where": "Seller Central › Reports › Returns; value of refunded orders.",
        "commission_label": "Amazon referral fee",
        "commission_where": "Seller Central › Payments › Transaction view › Amazon fees (referral fee only). FBA fees go in Logistics.",
        "fees_label": "FBA / closing / storage fees",
        "fees_where": "Seller Central › Payments › FBA fulfilment fee, fixed closing fee, storage fee.",
    },
    "marketplace": {
        "label": "Marketplace (billed commission)",
        "commission_mode": "billed",
        "has_pg": False,
        "has_ship_fee": False,
        "mkt_label": "Marketplace ads (sponsored listings, banners)",
        "mkt_where": "Seller panel › Ads / Promotions › spend for the month excluding GST.",
        "gmv_where": "Seller panel › Sales report › Gross sales incl. GST (Myntra: Partner Portal; Flipkart: Seller Hub; Nykaa marketplace: Seller Portal).",
        "disc_where": "Seller-funded discounts and coupon share from the settlement or promotions report.",
        "returns_where": "Seller panel › Returns / RTO report. Apparel marketplaces run heavy exchanges; enter them on the exchanges line.",
        "commission_label": "Marketplace commission & fees",
        "commission_where": "Settlement report › commission, fixed fee, collection fee, shipping fee charged by the platform.",
        "fees_label": "Platform fixed / listing fees",
        "fees_where": "Monthly subscription, cataloguing, listing or 'shared cost' charges on the settlement.",
    },
    "b2b_marketplace": {
        "label": "Marketplace on B2B terms (netted margin)",
        "commission_mode": "netted",      # partner raises PO, buys stock, brand invoices net of margin
        "has_pg": False,
        "has_ship_fee": False,
        "mkt_label": "Marketing & visibility on partner platform",
        "mkt_where": "Debit notes or invoices from the partner for banners, campaigns, visibility.",
        "gmv_where": "Partner's sell-through report at MRP incl. GST. If unavailable, use your invoice value grossed up by the agreed margin.",
        "disc_where": "Consumer discounts you funded per the partner's debit note.",
        "returns_where": "Stock returned or reversed under the PO, at MRP. Usually small.",
        "margin_label": "Partner margin (per PO / agreement)",
        "margin_where": "Difference between MRP and your invoice price to the partner, per the trade agreement.",
    },
    "qcom": {
        "label": "Quick commerce",
        "commission_mode": "netted",
        "has_pg": False,
        "has_ship_fee": False,
        "mkt_label": "Quick-commerce ads (sponsored listings)",
        "mkt_where": "Blinkit / Zepto / Instamart brand dashboard › Ads › spend excluding GST.",
        "gmv_where": "Partner dashboard › GMV at MRP incl. GST for the month.",
        "disc_where": "Leave blank here if you enter brand-funded promos on the Consumer promotions line.",
        "returns_where": "Expiry or damage returns reversed on the PO. Usually near zero.",
        "margin_label": "Quick-commerce partner margin",
        "margin_where": "MRP less your invoice price to the partner, per the trade agreement (typically 25–40%).",
        "promo_label": "Consumer promotions funded by brand",
        "promo_where": "Partner's debit note for brand-funded discounts, or dashboard › Promotions › brand share.",
    },
    "offline": {
        "label": "Offline retail / distribution",
        "commission_mode": "netted",
        "has_pg": False,
        "has_ship_fee": False,
        "mkt_label": "Trade marketing (visibility, displays, activations)",
        "mkt_where": "Invoices or debit notes for shelf fees, displays, in-store activations.",
        "gmv_where": "Sell-in to distributors or retailers valued at MRP incl. GST. If you only know your invoice value, gross it up by the trade margin.",
        "disc_where": "Consumer schemes you funded (price-offs, GWPs) per debit notes.",
        "returns_where": "Damaged or expired stock taken back, at MRP.",
        "margin_label": "Distributor + retailer margin",
        "margin_where": "MRP less your invoice price, per the trade agreement (typically 25–40% of MRP).",
        "staff_label": "Sales staff / beauty advisors in stores",
        "staff_where": "Salaries and incentives of people placed in stores, if you treat them as a selling cost.",
        "schemes_label": "Testers, samples & retailer schemes",
        "schemes_where": "Testers, GWPs, extra margin or scheme payouts billed by the retailer.",
    },
}

# ---------------------------------------------------------------------------------------------------
# Archetypes: defaults and bands. GST rates are fractions.
# ---------------------------------------------------------------------------------------------------
ARCHETYPES = {
    "bpc": {
        "label": "Beauty & personal care",
        "gst": 0.18,
        "returns_split": False,
        "bands": {"gm": (0.45, 0.75), "returns_pct_gmv": (0.0, 0.15), "gst": (0.17, 0.19),
                  "logistics_pct": (0.05, 0.15), "dio": (30, 150), "dso": (0, 60)},
        "cogs_note": "Contract-manufactured: product cost + primary packaging per unit × units sold this month. Include the cost of testers and samples given away.",
    },
    "fnb": {
        "label": "Food & beverage / nutrition",
        "gst": 0.12,
        "returns_split": False,
        "bands": {"gm": (0.25, 0.55), "returns_pct_gmv": (0.0, 0.08), "gst": (0.04, 0.19),
                  "logistics_pct": (0.05, 0.15), "dio": (20, 90), "dso": (0, 60)},
        "cogs_note": "Product + conversion (job-work, plant labour) + primary packaging for units sold. Expiry write-offs go to Write-offs, not COGS.",
    },
    "apparel": {
        "label": "Apparel & accessories",
        "gst": 0.10,
        "returns_split": True,
        "bands": {"gm": (0.40, 0.70), "returns_pct_gmv": (0.20, 0.60), "gst": (0.04, 0.13),
                  "logistics_pct": (0.08, 0.25), "dio": (45, 220), "dso": (0, 45)},
        "cogs_note": "Fabric + job-work + trims + packaging for units sold. Liquidation of old seasons below cost goes to Write-offs.",
    },
    "other": {
        "label": "Other",
        "gst": 0.18,
        "returns_split": False,
        "bands": {"gm": (0.20, 0.80), "returns_pct_gmv": (0.0, 0.30), "gst": (0.04, 0.19),
                  "logistics_pct": (0.03, 0.25), "dio": (20, 220), "dso": (0, 60)},
        "cogs_note": "Landed cost of units sold: purchase price + inbound freight + duties, or manufacturing cost + primary packaging.",
    },
}

# ---------------------------------------------------------------------------------------------------
# Placement decisions. Each has options; the chosen option changes which lines appear or where.
# ---------------------------------------------------------------------------------------------------
DECISIONS = {
    "qcom_promo": {
        "question": "Brand-funded consumer promotions on quick commerce: revenue deduction or marketing cost?",
        "options": {"deduction": "Deduct from net sales before gross margin (investor standard; GM% reads lower)",
                    "marketing": "Treat as a marketing cost below CM1 (GM% reads higher; CM2 and below unchanged)"},
        "default": "deduction",
        "applies_if": lambda cfg: any(c["type"] == "qcom" for c in cfg["channels"]),
        "why": "Moves GM% by 5–6 points in food brands. Investors expect the deduction view; your auditor may prefer marketing. CM3 and EBITDA are identical either way.",
    },
    "ship_fee": {
        "question": "Shipping and COD fees you collect from website customers: add to revenue or net against logistics?",
        "options": {"cost": "Net against logistics cost (keeps GMV clean)",
                    "revenue": "Add to revenue above net sales"},
        "default": "cost",
        "applies_if": lambda cfg: any(c["type"] == "website" for c in cfg["channels"]),
        "why": "Both are accepted. Netting keeps AOV and GMV comparable with marketplaces that never show this fee.",
    },
    "store_staff": {
        "question": "Salaries of sales staff or beauty advisors placed in stores: selling cost in the offline channel, or people cost below CM3?",
        "options": {"cm2": "Selling cost inside the offline channel P&L (shows true offline economics)",
                    "fixed": "People cost on the consolidated P&L"},
        "default": "cm2",
        "applies_if": lambda cfg: any(c["type"] == "offline" for c in cfg["channels"]),
        "why": "Store staff scale with doors, not with head office. Keeping them in the channel shows whether offline pays for itself.",
    },
    "exchanges": {
        "question": "Exchanges in apparel: count the returned unit as a return and the replacement as new gross sales, or net them out?",
        "options": {"gross": "Return at full value; replacement counted as new gross sales (matches marketplace reports)",
                    "net": "Net: exclude both legs, record only the extra logistics"},
        "default": "gross",
        "applies_if": lambda cfg: cfg["archetype"] == "apparel",
        "why": "Marketplace reports show exchanges as returns plus new orders, so gross is easier to reconcile. Either way, do not count the replacement's logistics twice.",
    },
}

# ---------------------------------------------------------------------------------------------------
# Channel-tab lines, in display order.
# kind: input | formula | pct | header | blank
# formula: template with {key} placeholders resolved to same-column cells; missing keys resolve to 0.
# applies: set of channel types, or "all". cond: optional callable(cfg, channel) -> bool.
# labels/notes may vary by channel type via ct[...] lookups; the generator substitutes.
# ---------------------------------------------------------------------------------------------------
def _ct(field, default=""):
    return lambda ct: ct.get(field, default)

CHANNEL_LINES = [
    dict(key="h_rev", kind="header", label="REVENUE"),
    dict(key="gmv", kind="input", label="Gross sales (GMV) incl. GST", where=_ct("gmv_where"),
         what="Everything customers ordered and you shipped this month, valued at the price they paid before any discount, including GST.",
         mistake="Entering Shopify 'Total sales' (already net of discounts and returns) or entering values excluding GST. Enter the gross, GST-inclusive number and let the sheet deduct."),
    dict(key="discounts", kind="input", label="Consumer discounts & coupons", where=_ct("disc_where"),
         what="Discounts the shopper saw at checkout: coupon codes, automatic discounts, sale price-offs. Funded by you.",
         mistake="Mixing platform commission in here. Commission is what the platform keeps; discounts are what the customer did not pay."),
    dict(key="channel_margin", kind="input", label=_ct("margin_label", "Channel / partner margin"), where=_ct("margin_where"),
         applies={"b2b_marketplace", "qcom", "offline"},
         what="The partner's margin when they buy your stock or raise a purchase order: MRP less what you invoice them.",
         mistake="Forgetting this line makes GM% look like a website channel. If your invoice already excludes it, GMV must be grossed up to MRP or the line stays zero."),
    dict(key="returns", kind="input", label="Returns, RTO & cancellations after dispatch", where=_ct("returns_where"),
         cond=lambda cfg, ch: not ARCHETYPES[cfg["archetype"]]["returns_split"],
         what="Value (at selling price incl. GST) of orders that came back: undelivered COD (RTO), customer returns, cancellations after dispatch.",
         mistake="Counting only refunds. RTO on COD orders is the bigger number for most website channels and never shows as a refund."),
    dict(key="rto", kind="input", label="RTO (undelivered / refused, returned to origin)", where=_ct("returns_where"),
         cond=lambda cfg, ch: ARCHETYPES[cfg["archetype"]]["returns_split"],
         what="Orders the courier could not deliver, mostly COD refusals, valued at selling price incl. GST.",
         mistake="Netting RTO into 'returns'. RTO is a delivery problem; returns are a product or fit problem. They need different fixes."),
    dict(key="returns_refund", kind="input", label="Customer returns refunded", where=_ct("returns_where"),
         cond=lambda cfg, ch: ARCHETYPES[cfg["archetype"]]["returns_split"],
         what="Delivered orders the customer sent back for a refund, at selling price incl. GST. Include refunds issued as store credit or gift cards.",
         mistake="Ignoring gift-card refunds because no cash left. They still reverse revenue and create a liability."),
    dict(key="exchanges", kind="input", label="Exchanges (returned for another size / item)", where=_ct("returns_where"),
         cond=lambda cfg, ch: ARCHETYPES[cfg["archetype"]]["returns_split"],
         what="Delivered orders returned and replaced. Enter the value of the returned unit at selling price incl. GST.",
         mistake="Counting the replacement's shipping cost twice, once in forward logistics and once as an exchange cost. Count it once."),
    dict(key="ship_fee", kind="input", label="Shipping & COD fees collected from customers", applies={"website"},
         cond=lambda cfg, ch: cfg["decisions"].get("ship_fee") == "revenue",
         where="Shopify › Analytics › Shipping charges, plus COD handling fees charged to customers.",
         what="Fees the customer paid you for delivery or COD handling.",
         mistake="Treating this as marketing or as a discount. It is money in, either as revenue (here) or as a reduction of logistics cost."),
    dict(key="pretax_net", kind="formula", label="Net revenue before GST",
         formula="{gmv}-{discounts}-{channel_margin}-{returns}-{rto}-{returns_refund}-{exchanges}+{ship_fee}",
         what="What is left after discounts, partner margin and returns. Still includes GST."),
    dict(key="gst", kind="formula", label="Less: GST (output tax)", formula="{pretax_net}-{pretax_net}/(1+{gst_rate})",
         what="GST collected on your net revenue, at the rate set on Start Here for this channel. Overwrite with your GSTR-1 figure if you have it.",
         mistake="Deducting GST as a percentage of the gross number instead of backing it out (÷ 1.18, not × 0.18)."),
    dict(key="nsr", kind="formula", label="NET SALES (post GST)", bold=True, formula="{pretax_net}-{gst}",
         what="The number every ratio below is measured against. Investors call it net sales, NSR or NMV."),
    dict(key="promo_ded", kind="input", label=_ct("promo_label", "Consumer promotions funded by brand"), where=_ct("promo_where"),
         applies={"qcom"}, cond=lambda cfg, ch: cfg["decisions"].get("qcom_promo", "deduction") == "deduction",
         what="Price-offs the shopper sees on the quick-commerce app that you fund, per the partner's debit note.",
         mistake="Leaving it inside 'discounts' when the partner also funds part of the promo. Enter only your share."),
    dict(key="nsr_post", kind="formula", label="Net sales after brand-funded promotions", formula="{nsr}-{promo_ded}",
         applies={"qcom"}, cond=lambda cfg, ch: cfg["decisions"].get("qcom_promo", "deduction") == "deduction",
         what="Net sales after the promotions you fund. Gross margin is measured from here."),
    dict(key="blank1", kind="blank"),
    dict(key="h_cogs", kind="header", label="COST OF GOODS"),
    dict(key="cogs", kind="input", label="Cost of goods sold (product + conversion + primary packaging)",
         where="Units sold this month × landed cost per unit, from your costing sheet. Not purchases made this month.",
         what="The cost of the units you actually sold: product, manufacturing or job-work, and the packaging that touches the product.",
         mistake="Entering this month's purchases or factory bills. Purchases go to inventory; COGS is only what left the warehouse as sales. Secondary packaging (shippers, fillers) goes in Logistics."),
    dict(key="gm", kind="formula", label="GROSS MARGIN", bold=True, formula="{nsr_base}-{cogs}",
         what="Net sales less cost of goods. The first number an investor looks at."),
    dict(key="gm_pct", kind="pct", label="Gross margin %", formula="{gm}/{nsr}"),
    dict(key="blank2", kind="blank"),
    dict(key="h_ful", kind="header", label="FULFILMENT & CHANNEL COSTS"),
    dict(key="logistics", kind="input", label="Logistics: forward, reverse, RTO & COD charges, secondary packaging",
         where="Shiprocket / Delhivery / Bluedart invoices for the month excl. GST, plus shipper cartons and fillers. Amazon: FBA fulfilment fee.",
         what="Getting product to the customer and back: courier, 3PL pick-pack, RTO charges, COD collection fee, shipping cartons.",
         mistake="Leaving out reverse and RTO charges, which can be 30–50% of forward cost in COD-heavy or apparel businesses."),
    dict(key="ship_fee_cost", kind="input", label="Less: shipping & COD fees collected from customers", applies={"website"},
         cond=lambda cfg, ch: cfg["decisions"].get("ship_fee", "cost") == "cost",
         where="Shopify › Analytics › Shipping charges, plus COD handling fees charged to customers. Enter as a positive number; the sheet subtracts it.",
         what="Fees customers paid you for delivery or COD, netted against logistics.",
         mistake="Entering it as a negative. Enter positive; the formula subtracts."),
    dict(key="warehousing", kind="input", label="Warehousing & operations (rent, staff, packing labour)",
         where="Warehouse rent, warehouse staff, packing consumables for the month. If shared across channels, split by orders.",
         what="Cost of storing and handling stock, before it ships.",
         mistake="Putting warehouse staff under Salaries. They scale with orders, so they belong here."),
    dict(key="pg", kind="input", label="Payment gateway charges", applies={"website"},
         where="Razorpay / PayU / Cashfree statement › fees for the month excl. GST. Typically 1.8–2.2% of prepaid collections.",
         what="What the gateway kept from prepaid collections.",
         mistake="Ignoring it because the payout arrives net. Gross up collections and show the fee."),
    dict(key="commission", kind="input", label=_ct("commission_label", "Marketplace commission"), where=_ct("commission_where"),
         applies={"amazon", "marketplace"},
         what="What the platform charged you for the sale: referral or commission, collection fee, platform shipping fee.",
         mistake="Netting it out of GMV so it disappears. When the platform bills commission and you invoice the shopper, it is a cost here, not a revenue deduction."),
    dict(key="platform_fees", kind="input", label=_ct("fees_label", "Platform fixed / listing fees"), where=_ct("fees_where"),
         applies={"amazon", "marketplace"},
         what="Fixed platform charges that do not scale with each order: subscription, closing fee, storage, cataloguing.",
         mistake="Mixing them into commission. Keep fixed fees separate so commission % stays comparable month to month."),
    dict(key="cm1", kind="formula", label="CONTRIBUTION MARGIN 1 (CM1)", bold=True,
         formula="{gm}-{logistics}+{ship_fee_cost}-{warehousing}-{pg}-{commission}-{platform_fees}",
         what="Margin after getting the product to the customer and paying the channel. What is left to pay for marketing."),
    dict(key="cm1_pct", kind="pct", label="CM1 %", formula="{cm1}/{nsr}"),
    dict(key="blank3", kind="blank"),
    dict(key="h_mkt", kind="header", label="MARKETING & SELLING"),
    dict(key="perf_mkt", kind="input", label=_ct("mkt_label"), where=_ct("mkt_where"),
         what="Paid media and channel advertising that drives this channel's sales this month, excluding GST (you claim the input credit).",
         mistake="Entering the GST-inclusive invoice. Also: agency retainers and content production are brand costs on the Consolidated tab, not here."),
    dict(key="promo_mkt", kind="input", label=_ct("promo_label", "Consumer promotions funded by brand"), where=_ct("promo_where"),
         applies={"qcom"}, cond=lambda cfg, ch: cfg["decisions"].get("qcom_promo") == "marketing",
         what="Price-offs you fund on the quick-commerce app, treated here as a marketing cost.",
         mistake="Also deducting them from net sales. Pick one place; you chose marketing."),
    dict(key="store_staff", kind="input", label=_ct("staff_label", "Store sales staff"), where=_ct("staff_where"),
         applies={"offline"}, cond=lambda cfg, ch: cfg["decisions"].get("store_staff", "cm2") == "cm2",
         what="People placed in stores to sell: beauty advisors, promoters, sales officers.",
         mistake="Also including them under Salaries on the Consolidated tab. Once only."),
    dict(key="schemes", kind="input", label=_ct("schemes_label", "Testers, samples & retailer schemes"), where=_ct("schemes_where"),
         applies={"offline"},
         what="Testers, gift-with-purchase, extra margin or scheme payouts the retailer bills you for.",
         mistake="Hiding these in discounts. They are the real cost of offline and should be visible."),
    dict(key="cm2", kind="formula", label="CONTRIBUTION MARGIN 2 (CM2)", bold=True,
         formula="{cm1}-{perf_mkt}-{promo_mkt}-{store_staff}-{schemes}",
         what="Margin after channel-level marketing and selling costs. Positive CM2 means the channel pays for its own growth."),
    dict(key="cm2_pct", kind="pct", label="CM2 %", formula="{cm2}/{nsr}"),
    dict(key="blank4", kind="blank"),
    dict(key="h_memo", kind="header", label="MEMO"),
    dict(key="orders", kind="input", label="Orders shipped (count)", fmt="int",
         where="Shopify › Orders (fulfilled) or marketplace › Orders shipped. Offline / Qcom: units or cases invoiced.",
         what="Number of orders that went out. Used for AOV.", mistake="Counting orders placed rather than shipped; cancellations inflate it."),
    dict(key="aov", kind="formula", label="Average order value incl. GST", fmt="money", formula="{gmv}/{orders}", guard="{orders}",
         what="GMV per shipped order."),
    dict(key="roas", kind="formula", label="RoAS (net sales ÷ marketing)", fmt="mult", formula="{nsr}/{perf_mkt}", guard="{perf_mkt}",
         what="Net sales generated per rupee of marketing in this channel. Below 1.5× on a website channel is a red flag unless the brand is very new."),
    dict(key="returns_pct", kind="pct", label="Returns & RTO % of GMV", formula="({returns}+{rto}+{returns_refund}+{exchanges})/{gmv}"),
    dict(key="disc_pct", kind="pct", label="Discounts % of GMV", formula="{discounts}/{gmv}"),
    dict(key="mkt_pct", kind="pct", label="Marketing % of net sales", formula="({perf_mkt}+{promo_mkt})/{nsr}"),
    dict(key="log_pct", kind="pct", label="Logistics % of net sales", formula="({logistics}-{ship_fee_cost}+{warehousing})/{nsr}"),
]

# Lines summed from channel tabs onto the Consolidated tab, in order. Keys must exist in CHANNEL_LINES.
CONSOLIDATED_SUM_KEYS = [
    ("h_rev", "REVENUE"),
    ("gmv", None), ("discounts", None), ("channel_margin", "Channel / partner margins (netted channels)"),
    ("returns", None), ("rto", None), ("returns_refund", None), ("exchanges", None), ("ship_fee", None),
    ("pretax_net", None), ("gst", None), ("nsr", None), ("promo_ded", "Consumer promotions funded by brand (deduction)"),
    ("nsr_post", None),
    ("blank1", None), ("h_cogs", None), ("cogs", None), ("gm", None), ("gm_pct", None),
    ("blank2", None), ("h_ful", None), ("logistics", None), ("ship_fee_cost", None), ("warehousing", None), ("pg", None),
    ("commission", "Marketplace commissions (billed channels)"), ("platform_fees", None), ("cm1", None), ("cm1_pct", None),
    ("blank3", None), ("h_mkt", None), ("perf_mkt", "Performance & channel marketing (all channels)"),
    ("promo_mkt", "Consumer promotions funded by brand (marketing)"), ("store_staff", None), ("schemes", None),
    ("cm2", None), ("cm2_pct", None),
]

# Lines that exist only on the Consolidated tab, after CM2.
CONSOLIDATED_LINES = [
    dict(key="brand_mkt", kind="input", label="Brand marketing & content (campaigns, shoots, influencer retainers, PR, agency)",
         where="Agency retainers, photoshoots, influencer fees not tied to a sale, PR, brand campaigns. Excl. GST.",
         what="Marketing that builds the brand rather than a specific channel's sales this month.",
         mistake="Splitting it into channels by guesswork. Keep it here so CM2 by channel stays honest."),
    dict(key="cm3", kind="formula", label="CONTRIBUTION MARGIN 3 (CM3)", bold=True, formula="{cm2}-{brand_mkt}",
         what="Margin after all marketing. This is the number that should turn positive first as you scale."),
    dict(key="cm3_pct", kind="pct", label="CM3 %", formula="{cm3}/{nsr}"),
    dict(key="blank5", kind="blank"),
    dict(key="h_fixed", kind="header", label="FIXED COSTS"),
    dict(key="people", kind="input", label="People: salaries, contractors, founder pay, employee benefits",
         where="Payroll for the month incl. PF/ESI and contractors. Exclude warehouse staff (Logistics) and store staff if entered in the offline channel.",
         what="Everyone on the team who is not in the warehouse or a store.",
         mistake="Leaving out founder salary because it is unpaid. Enter what you would pay; investors add it back anyway."),
    dict(key="tech", kind="input", label="Technology: Shopify, apps, SaaS, domains",
         where="Shopify bill, app subscriptions, Zoho/Notion/Slack, hosting. Excl. GST.",
         what="Software that runs the business.", mistake="Putting Shopify transaction fees here; those are payment gateway costs."),
    dict(key="rent_admin", kind="input", label="Office rent, utilities, travel & admin",
         where="Office rent, electricity, internet, travel, meals, insurance, bank charges.",
         what="Running the office.", mistake="Including warehouse rent, which belongs in Warehousing."),
    dict(key="legal_prof", kind="input", label="Legal, accounting & professional fees",
         where="CA, CS, lawyers, consultants.", what="Professional advisers.", mistake="Including agency retainers, which are brand marketing."),
    dict(key="sampling", kind="input", label="Sampling & free product (not campaign-led)",
         where="Cost of units given away outside a brand campaign: PR seeding, gifting, trade samples.",
         what="Product you did not sell and did not give as part of a specific campaign.",
         mistake="Leaving this inside COGS, which understates true gross margin."),
    dict(key="writeoffs", kind="input", label="Write-offs: expired, damaged, liquidated below cost",
         where="Stock written off or sold below cost this month, at cost.",
         what="Inventory losses. Non-cash but real.", mistake="Ignoring them until year end; monthly visibility is the point."),
    dict(key="op_ebitda", kind="formula", label="OPERATING EBITDA", bold=True,
         formula="{cm3}-{people}-{tech}-{rent_admin}-{legal_prof}-{sampling}-{writeoffs}",
         what="Profit before interest, depreciation, tax and one-offs. The bottom line an investor compares across brands."),
    dict(key="op_ebitda_pct", kind="pct", label="Operating EBITDA %", formula="{op_ebitda}/{nsr}"),
    dict(key="one_time", kind="input", label="One-time / exceptional costs",
         where="Fund-raise costs, legal settlements, relocation. Genuinely non-recurring only.",
         what="Costs that will not recur and should not be in the run-rate.",
         mistake="Calling every bad month 'one-time'. If it happens twice a year, it is operating."),
    dict(key="rep_ebitda", kind="formula", label="REPORTED EBITDA", bold=True, formula="{op_ebitda}-{one_time}",
         what="Operating EBITDA less one-offs."),
    dict(key="blank6", kind="blank"),
    dict(key="h_below", kind="header", label="BELOW EBITDA"),
    dict(key="dep", kind="input", label="Depreciation & amortisation", where="From your CA, or leave blank until year end.",
         what="Non-cash charge on equipment, moulds, software.", mistake="None; small brands can leave it blank."),
    dict(key="interest", kind="input", label="Interest & finance charges (net of interest earned)",
         where="Loan and credit-line interest paid, less FD interest earned.",
         what="Cost of borrowed money, net of what idle cash earned.",
         mistake="Adding FD interest above EBITDA to flatter it. It belongs here."),
    dict(key="pbt", kind="formula", label="PROFIT BEFORE TAX", bold=True, formula="{rep_ebitda}-{dep}-{interest}",
         what="What is left before income tax."),
    dict(key="blank7", kind="blank"),
    dict(key="h_ratios", kind="header", label="KEY RATIOS & MIX"),
    dict(key="nsr_growth", kind="pct", label="Net sales growth month on month", formula="MOM:{nsr}"),
    dict(key="mkt_total_pct", kind="pct", label="Total marketing % of net sales", formula="({perf_mkt}+{promo_mkt}+{brand_mkt})/{nsr}"),
    dict(key="roas_total", kind="formula", label="Blended RoAS (net sales ÷ all marketing)", fmt="mult",
         formula="{nsr}/({perf_mkt}+{promo_mkt}+{brand_mkt})", guard="({perf_mkt}+{promo_mkt}+{brand_mkt})"),
    dict(key="people_pct", kind="pct", label="People % of net sales", formula="{people}/{nsr}"),
    dict(key="fixed_pct", kind="pct", label="Fixed costs % of net sales", formula="({people}+{tech}+{rent_admin}+{legal_prof}+{sampling}+{writeoffs})/{nsr}"),
    # channel mix rows are appended by the generator
]

CASH_LINES = [
    dict(key="h_wc", kind="header", label="WORKING CAPITAL (closing balances at month end)"),
    dict(key="inventory", kind="input", label="Inventory at cost (finished goods + raw & packing material + goods in transit)",
         where="Stock count or inventory system at month end, valued at cost. Include stock at 3PLs, Amazon FBA, Qcom dark stores that is still yours.",
         what="Everything you own that has not been sold, at what it cost you.",
         mistake="Valuing at MRP, or forgetting stock sitting with Amazon and Qcom partners."),
    dict(key="receivables", kind="input", label="Receivables (money owed to you by platforms, partners, retailers)",
         where="Unsettled marketplace payouts + Qcom / B2B / distributor invoices unpaid + COD remittances pending from couriers.",
         what="Sales you have made but not been paid for yet.",
         mistake="Forgetting COD cash sitting with the courier for 7–10 days."),
    dict(key="payables", kind="input", label="Payables (money you owe suppliers, agencies, platforms)",
         where="Unpaid supplier, manufacturer, courier, agency and ad-platform invoices at month end.",
         what="Bills you have received but not paid.",
         mistake="Excluding credit-card balances used for ads. They are payables."),
    dict(key="nwc", kind="formula", label="NET WORKING CAPITAL", bold=True, formula="{inventory}+{receivables}-{payables}",
         what="Cash tied up in running the business. Growth usually eats cash here before it shows profit."),
    dict(key="dio", kind="formula", label="Inventory days (on COGS)", fmt="days", formula="{inventory}/{x_cogs}*30", guard="{x_cogs}",
         what="How many days of sales your stock covers. Above your archetype band means cash is sitting on shelves."),
    dict(key="dso", kind="formula", label="Receivable days (on net sales)", fmt="days", formula="{receivables}/{x_nsr}*30", guard="{x_nsr}",
         what="How long customers and platforms take to pay you."),
    dict(key="dpo", kind="formula", label="Payable days (on COGS)", fmt="days", formula="{payables}/{x_cogs}*30", guard="{x_cogs}",
         what="How long you take to pay suppliers. Long is good for cash, bad for relationships."),
    dict(key="ccc", kind="formula", label="Cash conversion cycle (days)", fmt="days", formula="{dio}+{dso}-{dpo}",
         what="Days between paying for stock and getting paid for it. Lower is better; negative means suppliers fund your growth."),
    dict(key="blank8", kind="blank"),
    dict(key="h_cash", kind="header", label="CASH FLOW"),
    dict(key="open_cash", kind="input_first", roll_from="close_cash", label="Opening cash (bank + wallets + FDs)", where="Bank balances on the 1st. Only the first month is typed; later months roll forward.",
         what="Cash at the start of the month.", mistake="Typing every month. Only month one is an input; the rest are formulas."),
    dict(key="x_ebitda", kind="link", label="Reported EBITDA (from Consolidated P&L)", link=("Consolidated P&L", "rep_ebitda")),
    dict(key="d_nwc", kind="formula", label="Less: increase in working capital", formula="PREV:{nwc}", what="Cash absorbed (or released) by inventory, receivables and payables moving."),
    dict(key="capex", kind="input", label="Less: capex (equipment, moulds, fit-outs, software builds)", where="Asset purchases this month.",
         what="Money spent on things that last more than a year.", mistake="Putting capex in the P&L as an expense."),
    dict(key="x_interest", kind="link", label="Less: interest & finance charges (from Consolidated P&L)", link=("Consolidated P&L", "interest")),
    dict(key="tax_paid", kind="input", label="Less: taxes paid (income tax, net GST paid)", where="Advance tax, TDS deposited, net GST cash outflow.",
         what="Tax actually paid in cash this month.", mistake="Confusing GST collected with GST paid; only the net cash outflow goes here."),
    dict(key="equity_in", kind="input", label="Add: equity raised", where="Money received from investors or founders this month.",
         what="New equity money in.", mistake="Including convertible notes here and also under debt."),
    dict(key="debt_in", kind="input", label="Add: debt drawn less repaid", where="Loans, credit lines, venture debt drawn, net of principal repaid.",
         what="Net borrowing this month. Negative if you repaid more than you drew.", mistake="Entering repayments as positive."),
    dict(key="other_cash", kind="input", label="Other cash movements", where="Anything else: deposits paid, refunds received, corrections.",
         what="Catch-all so closing cash matches the bank.", mistake="Using it to hide a P&L gap. Explain any big number in a note."),
    dict(key="close_cash", kind="formula", label="CLOSING CASH", bold=True,
         formula="{open_cash}+{x_ebitda}-{d_nwc}-{capex}-{x_interest}-{tax_paid}+{equity_in}+{debt_in}+{other_cash}",
         what="Should equal your bank balance on the last day. If it does not, something above is misclassified."),
    dict(key="burn", kind="formula", label="Net burn (negative = cash consumed)", formula="{close_cash}-{open_cash}",
         what="Cash consumed this month, before financing is the honest view: add back equity and debt to see operating burn."),
    dict(key="op_burn", kind="formula", label="Operating burn (before equity & debt)", formula="{burn}-{equity_in}-{debt_in}",
         what="Cash the business itself consumed. The runway denominator."),
    dict(key="runway", kind="formula", label="Runway (months, on last 3 months' operating burn)", fmt="days", formula="RUNWAY",
         what="Closing cash divided by average operating burn over the last three months. Blank while burn is positive."),
]


# ---------------------------------------------------------------------------------------------------
# Starter questions offered after generation and printed on Start Here. Keyed by archetype and channel type.
# Kept in sync with references/faq.md section K.
# ---------------------------------------------------------------------------------------------------
STARTER_QUESTIONS = {
    "all": [
        "Which margin should I quote when an investor asks \"what are your margins?\"",
        "My ad platform's RoAS and this sheet's RoAS don't match. Which one is right?",
        "What goes in COGS this month if I bought stock for the next three months?",
        "Why does the P&L show a loss but the bank balance dropped much more?",
        "What would an investor ask me from these numbers?",
    ],
    "bpc": [
        "Should Nykaa be a revenue deduction or a cost, and why does it change my gross margin?",
        "Where do influencer codes, influencer retainers and shoots each go?",
    ],
    "fnb": [
        "Where do the promos I fund on Blinkit go, and why does GM% move when I change my mind?",
        "Where do expiry write-offs go, and how do I keep them out of COGS?",
    ],
    "apparel": [
        "RTO, returns, exchanges: which is which, and am I double-counting exchange shipping?",
        "Should I look at logistics as % of net sales or % of GMV?",
    ],
    "other": [],
    "website": ["What return rate and RoAS should I expect on COD-heavy orders?"],
    "amazon": ["Amazon referral fee, FBA fee, storage fee, closing fee: which line does each go to?"],
    "marketplace": ["Should two marketplaces share a tab, or when does one need its own?"],
    "b2b_marketplace": ["My B2B partner's margin comes off my invoice. How do I fill GMV and margin so GM% is comparable?"],
    "qcom": ["Why does quick commerce look profitable at gross margin and not at CM3?"],
    "offline": ["Why is my offline gross margin high and CM2 negative, and where do beauty advisors and testers go?"],
}


def starter_questions(cfg, n=6):
    qs = list(STARTER_QUESTIONS["all"][:3]) + STARTER_QUESTIONS.get(cfg["archetype"], [])
    for ch in cfg["channels"]:
        qs += STARTER_QUESTIONS.get(ch["type"], [])
    qs += STARTER_QUESTIONS["all"][3:]
    seen, out = set(), []
    for q in qs:
        if q not in seen:
            seen.add(q); out.append(q)
    return out[:n]
